class pelis:
    def __init__(self, nombres, cantidad, actor, actores):
        self.series = netflix (["Peaky Blinders", 1234567, 'Cillian Murphy,Paul Anderson,Helen McCrory', 6], ["The Umbrella Academy", 2434908, 'Tom Hopper,Emmy Raver-Lampman,Ellen Page,David Castañeda', 4])
        self.pelis = netflix (["Inmortales", 35, 'Mirtha Legrand,Carlitos Balá,Elizabeth The Second', 30],["Inception", 17319533, 'Leonardo DiCaprio,Ellen Page,Joseph Gordon-Levitt', 148], ["Batman Begins",4760183, 'Christian Bale,Leonardo DiCaprio,Cillian Murphy,Michael Caine', 140])
    def actorTrabajado()
        return self.nombreActores
    
class series:
    def __init__(self, nombres, cantidad):
        self.series = nombres
        self.videos = [netflix(n) for n in peliculas]

class netflix:
    def __init__(self, nombres, cantidad, actor, actores):
        self.series = nombres
        self.vistos = cantidad
        self.actor = actor
        self.actores = actores

        
print(f'el video mas visto [2]')

